## Numpy 1st class

In [2]:
!pip install nptyping beartype --upgrade --force




  Using cached nptyping-2.5.0-py3-none-any.whl (37 kB)
  Obtaining dependency information for beartype from https://files.pythonhosted.org/packages/46/8a/a90fe78c73958340ed6b6ab128a10598ad5f0ff57537ad17f6ccd1ad830b/beartype-0.16.4-py3-none-any.whl.metadata
  Using cached beartype-0.16.4-py3-none-any.whl.metadata (29 kB)
  Obtaining dependency information for numpy<2.0.0,>=1.20.0 from https://files.pythonhosted.org/packages/32/95/908d0caa051beae4f7c77652dbbeb781e7b717f3040c5c5fcaed4d3ed08f/numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached beartype-0.16.4-py3-none-any.whl (819 kB)
Using cached numpy-1.26.1-cp312-cp312-win_amd64.whl (15.5 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.1
    Uninstalling numpy-1.26.1:
      Successfully uninstalled numpy-1.26.1
  Attempting uninstall: beartype
    Found existing installation: beartype 0.16.4
    Uninstalling beartype-0.16.4:
   

In [2]:
import numpy as np

a : np.ndarray = np.array(1000)  # object to store

display(a) # prints
display(a.shape) # 0 dimantion
display(a.dtype)
display(type(a))
display(a.ndim)
display(a.size)
display(a.itemsize)

array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

## Vector type

In [3]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4])  # object to store [1,2,3,4] = vactor type single or one direction

display(f" object {a}") # prints
display(f"object shape {a.shape}") # 0 dimantion
display(f"object type {a.dtype}")
display(f"object type with global function {type(a)}")
display(f"Number of dimension {a.ndim}")
display(f"Total items in array : {a.size}")
display(f"{a.itemsize}") # print itemsize of object

' object [1 2 3 4]'

'object shape (4,)'

'object type int32'

"object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in array : 4'

'4'

# Matrix

In [4]:
import numpy as np

data = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

a : np.ndarray = np.array(data)

display(f" object {a}") # prints
display(f"object shape {a.shape}") # 0 dimantion
display(f"object type {a.dtype}")
display(f"object type with global function {type(a)}")
display(f"Number of dimension {a.ndim}")
display(f"Total items in array : {a.size}")
display(f"{a.itemsize}") # print itemsize of object

' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'object shape (3, 4)'

'object type int32'

"object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in array : 12'

'4'

# Numpy with NDArray typing support

In [10]:
from nptyping import NDArray, Shape, UInt64
from typing import Any
data : NDArray[Shape["10"], Any] = np.arange(1,11)

print(data)
print(data + 5) # hr item mai 5 add ho ga or ye kam hm list mai ni krwa skte

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [11]:
# ye operation perform ni ho ga list mai
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
d1 + 5

TypeError: can only concatenate list (not "int") to list

In [12]:
# ase perform ho ga likn as mia bht time lgy ga
d1 : list[int] = [1,2,3,4,5,6,7,8]
[i+5 for i in d1]

[6, 7, 8, 9, 10, 11, 12, 13]

In [13]:
%%time

data : NDArray[Shape["10"], Any] = np.arange(1,1000000)

data + 5

CPU times: total: 0 ns
Wall time: 9.96 ms


array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [14]:
%%time
data : list[int] = list(range(1,1000000))

[i +5 for i in data]

CPU times: total: 125 ms
Wall time: 124 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# numpy advanced operations vs list operations

In [2]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000  # normal python list
print(data[data])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [38]:
import numpy as np
from numpy.typing import NDArray


ndata: NDArray[np.int64] = np.arange(1, 21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy 1d functions

In [4]:
!pip show numpy

Name: numpy
Version: 1.26.1
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [7]:
!pip install -U numpy

In [3]:
import numpy as np


state_bank = np.array([1,7,8,10])
select = np.array([True, False,False, True])

print(state_bank[select])


[ 1 10]


In [41]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank % 2 == 0

array([False, False,  True,  True])

In [35]:
import numpy as np
from nptyping import NDArray, Shape, UInt64
state_bank : NDArray[Shape["10"],Any] = np.array([1, 7, 8, 10])
ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1, 100, 20)

display(state_bank)
display(ubl_bank)


array([ 1,  7,  8, 10])

array([23, 55, 92, 11, 24, 83,  7, 83, 39, 12, 10, 74, 86, 62, 27, 37, 26,
       34,  9,  9])

In [26]:
import numpy as np

state_bank = np.array([1, 7, 8, 10], dtype=np.int64)
result = state_bank % 2 == 0
print(result)
print(result.dtype)


[False False  True  True]
bool


In [34]:

import numpy as np
from nptyping import NDArray, Shape, UInt64

state_bank : NDArray[Shape["10"],Any] = np.array([1, 7, 8, 10])
ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1, 100, 20)

display(state_bank)
display(ubl_bank)

np.in1d(state_bank,ubl_bank) # first variable items length returned( jo result search ho ga us ko true kr de ga or jo ni search ho ga us ko false kr de ga)

array([ 1,  7,  8, 10])

array([ 2, 51, 97, 78, 22, 51, 11, 23, 85, 27, 68, 70, 35, 23, 97, 75, 14,
       74, 42, 46])

array([False, False, False, False])

In [39]:
import numpy as np
from nptyping import NDArray, Shape, UInt64

state_bank : NDArray[Shape["10"],Any] = np.array([1, 7, 8, 10])
ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1, 100, 20)

display(state_bank)
display(ubl_bank)

state_bank[np.in1d(state_bank,ubl_bank)] # display(state_bank) as k data mai se array([ 1,  7, 10] ye same data nikl dia. phli value ko dosri value mai search krwate hai(state_bank ko search krwate hai ubl_bank mai)

array([ 1,  7,  8, 10])

array([47, 60, 59, 31,  1,  7, 72, 10, 28, 63, 61, 30, 63, 52, 59,  4, 51,
       80, 87, 59])

array([ 1,  7, 10])

In [40]:
# 1d function
# function h state_bank mai se data ko search kre ga or ubl_bank mai or in against result dy de ga jo value match kren gey wo rhen gey or baki sb khtm ho jyn gey

np.intersect1d(state_bank,ubl_bank)

array([ 1,  7, 10])

In [42]:
# where() function mai condition lga skte hai

x : NDArray[Shape["5"],Any] = np.array([1,3,4,5,7])
y : NDArray[Shape["5"],Any] = np.array([6,3,2,5,100])

display(x)  # 1, 3, 4, 5, 7
display(y)  # 6, 3, 2, 5, 100  
np.where(x > y, x, y) # x or y k value compare kre ga jo value bri ho gey wo np.where mai show kre ga

array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

# Create Numpy arrrays

In [44]:
# numpy array bnana ke treqa

a : NDArray[Shape["Size,Size"],Any] = np.array([[1,2,3],[4,5,6]])  # 2 dimention array (3 row 3 column)
print(a)

a : NDArray[Shape["Size,Size"],Any] = np.array([[1,2],[4,5]])  # 2 dimention array (2 row 2 column)
print(a)

a : NDArray[Shape["Size,Size"],Any] = np.array([["A"],["B"]])  # 2 dimention array (1 row 1 column)
print(a)



[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [45]:
# staric (*) ka mtlb b same he h 

a : NDArray[Shape["*, *"],Any] = np.array([[1,2,3],[4,5,6]])  # 2 dimention array (3 row 3 column)
print(a)

a : NDArray[Shape["*, *"],Any] = np.array([[1,2],[4,5]])  # 2 dimention array (2 row 2 column)
print(a)

a : NDArray[Shape["*, *"],Any] = np.array([["A"],["B"]])  # 2 dimention array (1 row 1 column)
print(a)



[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


# Create any dimention array

In [47]:
# one dimention array

a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(a)

a : NDArray[Shape["Size"],Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [48]:
# two dimention array

a : NDArray[Shape["Size,Size"],Any] = np.arange(3*3).reshape(3,3)
print(a)

a : NDArray[Shape["Size,Size"],Any] = np.arange(5*3).reshape(5,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [53]:
# three dimention array

a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print("2*3*3",a)

print("================================================================")

a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print("5*2*2",a)

2*3*3 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
5*2*2 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [55]:
# three dimention
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)

# Slicing
a[::2,::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [56]:
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:

np.asarray([1,2,3])

array([1, 2, 3])

In [58]:
# jitne 0 kahen gy uthne zero pas kre ga
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
# 2 row 2 column mai 0 hna chye
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [60]:

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [61]:
# a mai jitne b row or column hai on mai 1 likh do
a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)

np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
# 1st or last wala column row show kre

a : NDArray[Shape["Size,Size,Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[[0,-1],::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [65]:

ndata : NDArray[Shape["20"],Any] = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax()) # sb se bri value ka index number btata h
print(ndata.argmin())
print(ndata.mean())
print(ndata.std())
print(ndata.sum())
print(ndata.cumsum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
0
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
